---
# tasks file for ssh_keygen
- name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa.pub
  ansible.builtin.user:
    name: "{{user_name}}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa.pub

- name: Sync Pull task - Executed on  the Destination host "{{host2}}"
  hosts: "{{host1}}"
  user: "{{user_name}}"
  tasks:   
    - name: Copy the file from {{host1}} to {{host2}} using Method Pull
      tags: sync-pull
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: "{{host2}}"
      register: syncfile
      run_once: true
      with_items:
       - "~/{{user_name}}/.ssh/id_rsa.pub"