# tasks file for tomcat 
- name: Downloading required tomcat
  get_url:
     url: "{{tomcat_url}}"
     dest: /usr/local
      
- name: Extracting downloaded tomcat
  unarchive:
    src: "/usr/local/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
    dest: /usr/local
    remote_src: yes

#- name: Renaming tomcat home
 # command: mv /usr/local/apache-tomcat-{{req_tomcat_ver}} /usr/local/latest

- name: Replacing default port with required port
  template:
    src: server.xml.j2
    dest: /usr/local/latest/conf/server.xml
  notify: start_tomcat
